[install]
is_configured = false
build = 1

[launcher]
author = Paul Metcalf
version = 1.1.0
description = Dashboards for pfSense firewall, DNSBL, and pfBlockerNG IP activity.

[ui]
is_visible = true
label = pfSense Dashboards

[package]
id = pfsense-dashboards
check_for_updates = true

[id]
name = pfsense-dashboards
version = 1.1.0
