[pfsense_baseline_block_rate]
replicate = false

[pfsense_baseline_unique_sources_hourly]
replicate = false

[pfsense_ip_seen]
replicate = false

[pfsense_known_dnsbl_domains_prev7d]
replicate = false

[pfsense_known_iplog_dests_prev7d]
replicate = false
