# Macro definitions for pfSense Dashboards

[pfsense_index]
definition = index=pfsense
iseval = 0

[pfsense_normalize]
definition = eval transport_norm=lower(coalesce(transport,vendor_transport))
iseval = 0

[pfsense_base_filter]
definition = sourcetype=pfsense:* OR sourcetype=pfsense:filterlog OR sourcetype=pfsense:dnsbl OR sourcetype=pfsense:iplog
iseval = 0

[pfsense_token_filter]
definition = action=$action$ vendor_direction=$direction$ transport_norm=$transport$
iseval = 0
