[pfsense_baseline_block_rate]
external_type = kvstore
collection = pfsense_baseline_block_rate
fields_list = baseline_pct, updated_time

[pfsense_baseline_unique_sources_hourly]
external_type = kvstore
collection = pfsense_baseline_unique_sources_hourly
fields_list = baseline_per_hour, updated_time

[pfsense_ip_seen]
external_type = kvstore
collection = pfsense_ip_seen
fields_list = src_ip_norm, first_seen, last_seen

[pfsense_known_dnsbl_domains_prev7d]
external_type = kvstore
collection = pfsense_known_dnsbl_domains_prev7d
fields_list = blocked_domain, last_seen

[pfsense_known_iplog_dests_prev7d]
external_type = kvstore
collection = pfsense_known_iplog_dests_prev7d
fields_list = dest_ip_norm, last_seen
