[pfsense_baseline_block_rate]
filename = pfsense_baseline_block_rate.csv

[pfsense_baseline_unique_sources_hourly]
filename = pfsense_baseline_unique_sources_hourly.csv

[pfsense_ip_seen]
filename = pfsense_ip_seen.csv

[pfsense_known_dnsbl_domains_prev7d]
filename = pfsense_known_dnsbl_domains_prev7d.csv

[pfsense_known_iplog_dests_prev7d]
filename = pfsense_known_iplog_dests_prev7d.csv
